title: Numismatics
baseURL: http://gazos6.github.io/02/
languageCode: cs-cz
publishDir: docs

menu:
  main:
    - name: Homepage
      url: /
      weight: 10
    - name: Archive
      identifier: post
      url: /post/
      weight: 20

params:
  description: Description of my new site - may it helps.
  authors: Authors

